// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06UPoFuKEyxArCZduqLp0h3DYbnRK_bQ',
    appId: '1:33755922806:web:a337f5915a947956c2fa57',
    messagingSenderId: '33755922806',
    projectId: 'fluttertsworkshop',
    authDomain: 'fluttertsworkshop.firebaseapp.com',
    storageBucket: 'fluttertsworkshop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtMjVRNIRYg6mXJlvUoPo1fluEZBiWIxE',
    appId: '1:33755922806:android:b31a43b505a24f9ec2fa57',
    messagingSenderId: '33755922806',
    projectId: 'fluttertsworkshop',
    storageBucket: 'fluttertsworkshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Z37BnxDtKWo1LlNH96Zbu1YbIewef44',
    appId: '1:33755922806:ios:838868c3ed9f8f4ec2fa57',
    messagingSenderId: '33755922806',
    projectId: 'fluttertsworkshop',
    storageBucket: 'fluttertsworkshop.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Z37BnxDtKWo1LlNH96Zbu1YbIewef44',
    appId: '1:33755922806:ios:838868c3ed9f8f4ec2fa57',
    messagingSenderId: '33755922806',
    projectId: 'fluttertsworkshop',
    storageBucket: 'fluttertsworkshop.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD06UPoFuKEyxArCZduqLp0h3DYbnRK_bQ',
    appId: '1:33755922806:web:4092f74a62f2b9bdc2fa57',
    messagingSenderId: '33755922806',
    projectId: 'fluttertsworkshop',
    authDomain: 'fluttertsworkshop.firebaseapp.com',
    storageBucket: 'fluttertsworkshop.appspot.com',
  );
}
